[profile.default]
src = "src"
out = "out"
libs = ["lib"]

evm_version = 'shanghai'
solc_version = '0.8.25'

# for openzeppelin deploy
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
optimizer = true
optimizer_runs = 200

fs_permissions = [{access="read-write" , path="."}]

[etherscan]
localnet = { key = "localnet", url = "http://127.0.0.1:8545", chain = 31337 }
holesky = { key = "holesky", url = "https://ethereum-holesky-rpc.publicnode.com", chain = 17000 }
xlayertest = { key = "xlayertest", url = "https://xlayertestrpc.okx.com", chain = 195 }
xlayer = { key = "xlayer", url = "https://rpc.xlayer.tech", chain = 196 }
